apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsenamilay-pgadmin
  labels:
    app: tsenamilay-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsenamilay-pgadmin
  template:
    metadata:
      labels:
        app: tsenamilay-pgadmin
    spec:
      containers:
        - name: tsenamilay-pgadmin
          image: dpage/pgadmin4
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-data
          ports:
            - name: pgadmin-port
              containerPort: 5050
          envFrom:
            - secretRef:
              name: tsenamilay-pgadmin-secret
            - configMapRef:
              name: tsenamilay-pgadmin-cm
      volumes:
        - name: pgadmin-data
          hostPath:
            path: /home/serveremit/tsenamilay/k8s/dev/pgadmin
            type: DirectoryOrCreate
