apiVersion: v1
kind: Service
metadata:
  name: user-database
spec:
  selector:
    app: tsenamilay-pgadmin-database
  type: LoadBalancer
  ports:
    - port: 5050
      targetPort: pgadmin-port
      protocol: TCP
