apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsenamilay-rabbitmq
  labels:
    app: tsenamilay-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsenamilay-rabbitmq
  template:
    metadata:
      labels:
        app: tsenamilay-rabbitmq
    spec:
      containers:
        - name: tsenamilay-rabbitmq
          image: rabbitmq:3.11.23-management
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
          ports:
            - name: rabbitmq-port
              containerPort: 5672
            - name: management-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: tsenamilay-global-secret
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: tsenamilay-global-cm
                  key: RABBITMQ_PASSWORD
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /home/serveremit/tsenamilay/k8s/dev/rabbitmq
            type: DirectoryOrCreate
