apiVersion: v1
kind: Service
metadata:
  name: message-broker
spec:
  selector:
    app: tsenamilay-rabbitmq
  type: LoadBalancer
  ports:
    - name: rabbitmq-port
      port: 5672
      targetPort: rabbitmq-port
      protocol: TCP
    - name: management-port
      port: 15672
      targetPort: management-port
      protocol: TCP
