apiVersion: v1
kind: Service
metadata:
  name: mongo-express-product
spec:
  selector:
    app: tsenamilay-mongo-express-product
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: express-port
      protocol: TCP
