apiVersion: v1
kind: Service
metadata:
  name: user-database
spec:
  selector:
    app: tsenamilay-user-database
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: user-db-port
      protocol: TCP
