apiVersion: v1
kind: Service
metadata:
  name: redis-stack
spec:
  selector:
    app: tsenamilay-redis
  type: LoadBalancer
  ports:
    - name: redis-port
      port: 6379
      targetPort: redis-port
      protocol: TCP
    - name: insight-port
      port: 8001
      targetPort: insight-port
      protocol: TCP
